platform :ios, '11.0'

target 'SkillSDK' do
  use_frameworks!

  pod 'AFNetworking', '~> 4.0'
  pod 'SocketRocket', '~> 0.6.0'

end

target 'SkillSDKTests' do
  use_frameworks!
  
  pod 'AFNetworking', '~> 4.0'
  pod 'SocketRocket', '~> 0.6.0'
end
